### ISSUE TITLE
A word with hyphen is not being suggested by spell checker.

### ISSUE THREAD

**Issue by AbhilashR2020** [inaka/sheldon#58]
Hi Team,

I have tested this sheldon spell checker utility. I did see, the the hyphen words are not suggested by the spell checker.
for example:
self-ownership
self-paid
self-painter
self-pampered
self-pampering
self-panegyric
self-parasitism
self-parricide
self-partiality
self-paying
self-peace

Is there something i am missing to validate this?.

**Comment by ferigis** [comment]
hi @AbhilashR2020,

Thanks for using Sheldon! :)

I am not sure if I am following you, I just tested this misspelled word and it seems it works fine:

```
6> sheldon:check("self-ownersheep").
#{bazinga =>
      <<"The only way you'd be able to make a contribution to science is if they resume sending chimps into space.">>,
  misspelled_words =>
      [#{candidates => ["self-ownership"],
         line_number => 1,word => "self-ownersheep"}]}
```

What is exactly the issue you are facing?

**Comment by AbhilashR2020** [comment]
Thanks for your quick response. 
Please find a sample what i am trying out.

sheldon:check("selfownership").
#{bazinga =>
      <<"The correct animal for inter-species super soldier is the koala. You would wind up with an army so cute, it coul"...>>,
  misspelled_words =>
      [#{candidates => [],line_number => 1,word => "selfownership"}]}
can i get **self-ownership** as candidate?

**Comment by ferigis** [comment]
oh I understand now. Let me check

**Comment by ferigis** [comment]
@AbhilashR2020 we just merged the fix, so it should work now on master. Today we will release a new version with the fix on hex.pm. Thanks!
